name: dart_vlc_ffi
description: package:dart_vlc internal dependency package.
version: 0.2.0
homepage: https://github.com/alexmercerind/dart_vlc
repository: https://github.com/alexmercerind/dart_vlc
documentation: https://github.com/alexmercerind/dart_vlc/blob/master/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ffi: ^2.1.4
  path: ^1.9.1

dev_dependencies:
  lints: ^6.0.0
